#!/bin/bash
FROM=iso-8859-1
CURRENTPATH=`pwd`
TO=UTF-8
ICONV="iconv -f $FROM -t $TO"
# Convert
find $CURRENTPATH -type f -name "*.[ch]" | while read fn; do
cp ${fn} ${fn}.bak
$ICONV < ${fn}.bak > ${fn}
# rm ${fn}.bak
done
